/*  spidrv.c - The simplest kernel module.

* Copyright (C) 2013 - 2016 Xilinx, Inc
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License along
*   with this program. If not, see <http://www.gnu.org/licenses/>.

*/
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>
#include <linux/device.h>

#include <linux/uaccess.h> /*for get user and put user*/
#include <linux/cdev.h>
#include <linux/delay.h>
#include <asm/io.h> //writel_relaxed

#include <linux/cdev.h>
#include "spidrv.h"

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Xilinx Inc.");
MODULE_DESCRIPTION
    ("spidrv - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "spidrv"
#define DEVICE_NAME "/dev/spi_dev"

/* Simple example of how to receive command line parameters to your module.
   Delete if you don't need them */
unsigned myint = 0xdeadbeef;
char *mystr = "default";

module_param(myint, int, S_IRUGO);
module_param(mystr, charp, S_IRUGO);

struct spidrv_local {
    int irq;
    unsigned long mem_start;
    unsigned long mem_end;
    void __iomem *base_addr;
};
/* Global variables*/
static void *g_spi_reg_baseaddr = 0;
static int g_major_num;

/* End */
static irqreturn_t spidrv_irq(int irq, void *lp)
{
    printk("spidrv interrupt\n");
    return IRQ_HANDLED;
}

static int spidrv_probe(struct platform_device *pdev)
{
    struct resource *r_irq; /* Interrupt resources */
    struct resource *r_mem; /* IO mem resources */
    struct device *dev = &pdev->dev;
    struct spidrv_local *lp = NULL;

    int rc = 0;
    dev_info(dev, "Device Tree Probing\n");
    /* Get iospace for the device */
    r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
    if (!r_mem) {
        dev_err(dev, "invalid address\n");
        return -ENODEV;
    }
    lp = (struct spidrv_local *) kmalloc(sizeof(struct spidrv_local), GFP_KERNEL);
    if (!lp) {
        dev_err(dev, "Cound not allocate spidrv device\n");
        return -ENOMEM;
    }
    dev_set_drvdata(dev, lp);
    lp->mem_start = r_mem->start;
    lp->mem_end = r_mem->end;

    if (!request_mem_region(lp->mem_start,
                lp->mem_end - lp->mem_start + 1,
                DRIVER_NAME)) {
        dev_err(dev, "Couldn't lock memory region at %p\n",
            (void *)lp->mem_start);
        rc = -EBUSY;
        goto error1;
    }

    lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
    if (!lp->base_addr) {
        dev_err(dev, "spidrv: Could not allocate iomem\n");
        rc = -EIO;
        goto error2;
    }
    g_spi_reg_baseaddr = (void *)(lp->base_addr);

    /* Get IRQ for the device */
    r_irq = platform_get_resource(pdev, IORESOURCE_IRQ, 0);
    if (!r_irq) {
        dev_info(dev, "spidrv at 0x%p mapped to 0x%p, irq = %d \n",
            lp->mem_start,
            lp->base_addr,
            lp->irq); 
        return 0;
    }
    lp->irq = r_irq->start;
    rc = request_irq(lp->irq, &spidrv_irq, 0, DRIVER_NAME, lp);
    if (rc) {
        dev_err(dev, "testmodule: Could not allocate interrupt %d.\n",
            lp->irq);
        goto error3;
    }

    dev_info(dev, "spidrv at 0x%p mapped to 0x%p, irq = %d \n",
        lp->mem_start,
        lp->base_addr,
        lp->irq); 
    return 0;
error3:
    free_irq(lp->irq, lp);
error2:
    release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
error1:
    kfree(lp);
    dev_set_drvdata(dev, NULL);
    return rc;
}

static int spidrv_remove(struct platform_device *pdev)
{
    struct device *dev = &pdev->dev;
    struct spidrv_local *lp = dev_get_drvdata(dev);
    free_irq(lp->irq, lp);
    iounmap(lp->base_addr);
    release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
    kfree(lp);
    dev_set_drvdata(dev, NULL);
    return 0;
}

#ifdef CONFIG_OF
static struct of_device_id spidrv_of_match[] = {
    { .compatible = "xlnx,SPI-MC-1.0", },
    { /* end of list */ },
};
MODULE_DEVICE_TABLE(of, spidrv_of_match);
#else
# define spidrv_of_match
#endif

void reg_write(volatile u32 offset, u32 value)
{
    #ifdef DBG_OPEN
        printk(KERN_INFO "base addr = 0x%x, offset = %d, value = %d \n", g_spi_reg_baseaddr, offset, value);
    #endif
    *((u32*)((u8*)g_spi_reg_baseaddr + offset) ) = value;
    //writel_relaxed(value,(unsigned int *)(g_spi_reg_baseaddr + offset));
    
    return;
}

unsigned int reg_read(volatile u32 offset)
{
    #ifdef DBG_OPEN
        printk("base addr = 0x%p, offset = 0x%x, after addr = 0x%p, value = 0x%x\n",
            g_spi_reg_baseaddr, offset, ((u8*)g_spi_reg_baseaddr + offset),
            *((u32*)((u8*)g_spi_reg_baseaddr + offset) ));
    #endif
    return (*((u32*)((u8*)g_spi_reg_baseaddr + offset) )) ;
    //return readl_relaxed((u32 *)(g_spi_reg_baseaddr + offset));
}


static int spidrv_open(struct inode *inode, struct file *file)
{

    SpiDev *spiDev;
    spiDev = container_of(inode->i_cdev, SpiDev, cdev);
    file->private_data = (void *)spiDev;
    if (spiDev == NULL) {
        printk(KERN_ERR, "SPI open error.\n");
    }
    
    try_module_get(THIS_MODULE);
    return 0;
}


static int spidrv_release(struct inode *inode, struct file *file)
{
#ifdef DEBUG
    printk(KERN_INFO "spi_dev_close(%p)\n", file);
#endif
    module_put(THIS_MODULE);
    return 0;
}

static ssize_t spidrv_read(struct file *file, char __user* buffer,
    size_t length, loff_t *offset)
{
    unsigned int readSize = 4;
    reg_write(SPI_RX_FIFO_CTL_OFFSET_ADDR, SPI_RX_FIFO_RDTRIG_MASK);
    udelay(1);
    unsigned int regData = reg_read(SPI_RX_DATA_OFFSET_ADDR);
    unsigned int bytesNum = regData & 0xFF;
    (void)copy_to_user(buffer, &regData, readSize);
    return bytesNum; 
}

static ssize_t spidrv_write(struct file *file, const char __user *buffer,
    size_t length, loff_t *offset)
{
    unsigned int dataBuffer[TOTAL_DATA_SEND_NUM] = {0};
    if (length > TOTAL_DATA_SEND_NUM * BYTE_NUM) {
        printk("[spidrv], Input length is wrong! \n", length);
        return 0;
    }
    copy_from_user((char*)dataBuffer, buffer, length);
    unsigned int i;
    for (i = 0; i < length / BYTE_NUM; i++) {
        reg_write(SPI_TX_DATA_OFFSET_ADDR, dataBuffer[i]);
        #ifdef DBG_OPEN
            printk("[spidrv], writeData[i] = %#x. \n", dataBuffer[i]);
        #endif
        udelay(2);
    }
    return length;
}

void spidrv_clear_rx_fifo(void)
{
    u32 test_value = 0;
    u32 control_reg_value = reg_read(SPI_RX_FIFO_CTL_OFFSET_ADDR);
    control_reg_value |= SPI_RX_FIFO_RST_MASK;
    reg_write(SPI_RX_FIFO_CTL_OFFSET_ADDR, control_reg_value);
    test_value = reg_read(SPI_RX_FIFO_CTL_OFFSET_ADDR);

    udelay(1);
    control_reg_value &= (~SPI_RX_FIFO_RST_MASK);
    reg_write(SPI_RX_FIFO_CTL_OFFSET_ADDR, control_reg_value);
    test_value = reg_read(SPI_RX_FIFO_CTL_OFFSET_ADDR);
    return;
}

void spidrv_clear_tx_fifo(void)
{
    u32 control_reg_value = reg_read(SPI_TX_FIFO_CTL_OFFSET_ADDR);
    control_reg_value |= SPI_TX_FIFO_RST_MASK;
    reg_write(SPI_TX_FIFO_CTL_OFFSET_ADDR, control_reg_value);
    udelay(2);
    control_reg_value &= (~SPI_TX_FIFO_RST_MASK);
    reg_write(SPI_TX_FIFO_CTL_OFFSET_ADDR, control_reg_value);
    return;    
}

void spidrv_clear_all_fifo(void)
{
    spidrv_clear_rx_fifo();
    spidrv_clear_tx_fifo();
    return;
}


long spidrv_ioctl(struct file *file, u32 ioctl_num, unsigned long ioctl_param)
{
    long ret = SUCCESS;
    RegOper regInfo = {0};
    switch(ioctl_num) {
        case CMD_RESET_RX_BUFFER:
            spidrv_clear_rx_fifo();
            break;
        case CMD_RESET_TX_BUFFER:
            spidrv_clear_tx_fifo();
            break;
        case CMD_RESET_ALL_BUFFER :
            spidrv_clear_all_fifo();
            break;
        case CMD_WRITE_REG:
            copy_from_user(&regInfo, (RegOper *)ioctl_param, sizeof(RegOper));
            reg_write(regInfo.regOffsetAddr, regInfo.regValue);
            break;
        case CMD_READ_REG:
            copy_from_user(&regInfo, (RegOper *)ioctl_param, sizeof(RegOper));
            regInfo.regValue = reg_read(regInfo.regOffsetAddr);
            ret = copy_to_user((RegOper *)ioctl_param, &regInfo, sizeof(RegOper));
            break;       
        default:
            printk(KERN_ERR, "The iotcl_num is wrong! \n");
            ret = IOCTL_FAIL;
            break;
    }

    return ret;
}


struct file_operations Fops =   {
    .owner          = THIS_MODULE,
    .open           = spidrv_open,
    .release        = spidrv_release,
    .read           = spidrv_read,
    .write          = spidrv_write,
    .unlocked_ioctl  = spidrv_ioctl,
};


struct class *spi_drv_class;

static struct platform_driver spidrv_driver = {
    .driver = {
        .name = DRIVER_NAME,
        .owner = THIS_MODULE,
        .of_match_table    = spidrv_of_match,
    },
    .probe        = spidrv_probe,
    .remove        = spidrv_remove,
};

static int __init spidrv_init(void)
{
    printk("<1>Hello module world.\n");
    printk("<1>Module parameters were (0x%08x) and \"%s\"\n", myint, mystr);

    /*register the character device */
    g_major_num = register_chrdev(0, DEVICE_NAME, &Fops);
    if (g_major_num < 0) {
        printk(KERN_ALERT"%s failed with \n","Sorry, registering the character device");
    }
    spi_drv_class = class_create(THIS_MODULE, "spi_dev");
    if (IS_ERR(spi_drv_class)) {
        printk("ERR:failed in create spi_drv_class.\n");    

        printk(KERN_INFO "If you want to talk to the device driver,\n");
        printk(KERN_INFO "create a device file by following command.\n\n");
        printk(KERN_INFO "mknod %s c %d 0\n\n", DEVICE_NAME, g_major_num);
        printk(KERN_INFO "The device file name is important, because\n");
        printk(KERN_INFO "the ioctl program assumes that's the file you'll use\n");
    } else {
        device_create(spi_drv_class, NULL, MKDEV(g_major_num,0), 0, "spi_dev");
    }
    return platform_driver_register(&spidrv_driver);
}


static void __exit spidrv_exit(void)
{
    unregister_chrdev(g_major_num, DEVICE_NAME);
    device_destroy(spi_drv_class,MKDEV(g_major_num,0));
    class_destroy(spi_drv_class);

    platform_driver_unregister(&spidrv_driver);
    printk(KERN_ALERT "Goodbye module world.\n");
}

module_init(spidrv_init);
module_exit(spidrv_exit);
